route:
  receiver: 'Mail Alert'
  # group_by: [ job ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
    - to: "email id"
      from: "email id"
      smarthost: smtp.gmail.com:587
      auth_username: "email id"
      auth_identity: "email id"
      auth_password: "passwd"
